spring:
  redis:
    database: 1
    host: localhost
    port: 6379
app:
  client:
    url: http://localhost:8081
  dao:
    dataSource:
      driverClass: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/demo?useUnicode=true&characterEncoding=utf-8
      username: postgres
      password: lp87
    jpa:
      dialect: com.fosung.framework.dao.dialect.PostgreSQL9DialectWithoutFK
      schema: public
  secure:
    auth:
      urlAuths:
        -
          url: /**
          filter: anon
    referer:
      enable: false
    xss:
      enable: false

